module.exports = {
    "version": "0.2",
    "ignorePaths": [
        "package-lock.json",
        "node_modules",
        "dist/integration.js",
    ],
    "ignoreWords": [
        "APGL",
        "APGM",
        "APGT",
        "apge",
        "dups",
        "tdec",
        "mula",
        "APGsembly",
        "apgs",
        "Boby",
        "strs",
        "tspan",
        "klass",
        "noreferrer",
        "noopener",
        "importmap",
        "popperjs",
        "deno",
        "Ackermann",
        "Thue",
        "Lindenmayer",
        "Utemp",
        "Bfrom",
        "curr",
        "luca",
        "npmjs",
        "genhtml",

        "subtractor",
        "Decompiled",
        "macrof", // テスト
    ],
};
