name: Test by Deno

permissions:
    contents: read

on:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        steps:
            - name: Git Checkout Deno Module
              uses: actions/checkout@v4
            - name: Install Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x # latest
            # - name: Lint Deno Module
            #   run: deno fmt --check
            # - name: Build Deno Module
            #   run: deno run --reload mod.ts
            - name: Run Test
              run: deno task t
